### ISSUE TITLE
OpenAI Connection Error

### ISSUE THREAD

**Issue by minhhoang1023** [Wytamma/write-the#16]
I kept on having this OpenAI Connection Error. I'm sure it's not because of the API Keys as I have tested via Postman.

Any idea what this might be?

<img width="1388" alt="image" src="https://github.com/Wytamma/write-the/assets/40023817/4fa9e444-2c78-43f7-8cd9-1ce4cd2c704b">

**Comment by Wytamma** [comment]
Hmm that seems to be a network issue with OpenAI... What command where you running?

```
An APIConnectionError indicates an issue connecting to OpenAI's services. This could be due to a network issue, proxy configuration, SSL certificates, or firewall rules.

When encountering an APIConnectionError, follow these steps:

Check your network settings and ensure you have a stable and fast internet connection.
Check your proxy configuration, SSL certificates, and firewall rules.
```
