### ISSUE TITLE
Does this only work for `.py` files?

### ISSUE THREAD

**Issue by TechDufus** [Wytamma/write-the#4]
Based on this line, I'm assuming this will only generate docs, etc... for python files?
https://github.com/Wytamma/write-the/blob/4b2a247c49a007d5d43f9dc8cd39de5709d80dc8/write_the/cli/main.py#L79

If that's accurate, will this support more file types / langs in the future? I think the simple syntax for this is great!

**Comment by Wytamma** [comment]
Hi @TechDufus! 

Yes currently I'm parsing the concrete syntax tree of python files to make sure the docstrings are inserted without messing up the code. However, that is probably a lot of over kill. I think it would be simple to use pattern matching to find functions/class definitions and insert the docstrings below or above them (depending on the language). 

This is definitely on the roadmap and I'll try to come up with something generalised in a future release. Cheers!
